import { WeatherData, LocationSearchResult, WeatherCondition } from '../types/weather';

// This is a mock API for demonstration purposes
// In a real app, you would connect to a real weather API

// Mock data for current location weather
const mockWeatherData: WeatherData = {
  location: {
    name: 'New York',
    region: 'New York',
    country: 'United States',
    latitude: 40.7128,
    longitude: -74.0060,
    timezone: 'America/New_York',
    localTime: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
  },
  current: {
    temperature: 72,
    feelsLike: 73,
    humidity: 65,
    windSpeed: 8,
    condition: 'partly-cloudy',
    description: 'Partly cloudy',
    uvIndex: 5,
    pressure: 1012,
    visibility: 10,
    time: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
  },
  daily: [
    {
      date: new Date().toLocaleDateString(),
      day: 'Today',
      tempHigh: 75,
      tempLow: 62,
      condition: 'partly-cloudy',
      precipitation: 10,
      humidity: 65,
      windSpeed: 8,
    },
    {
      date: new Date(Date.now() + 86400000).toLocaleDateString(),
      day: 'Tomorrow',
      tempHigh: 68,
      tempLow: 58,
      condition: 'rain',
      precipitation: 80,
      humidity: 75,
      windSpeed: 10,
    },
    {
      date: new Date(Date.now() + 86400000 * 2).toLocaleDateString(),
      day: getDayName(new Date(Date.now() + 86400000 * 2)),
      tempHigh: 62,
      tempLow: 54,
      condition: 'rain',
      precipitation: 90,
      humidity: 80,
      windSpeed: 12,
    },
    {
      date: new Date(Date.now() + 86400000 * 3).toLocaleDateString(),
      day: getDayName(new Date(Date.now() + 86400000 * 3)),
      tempHigh: 65,
      tempLow: 56,
      condition: 'cloudy',
      precipitation: 40,
      humidity: 70,
      windSpeed: 9,
    },
    {
      date: new Date(Date.now() + 86400000 * 4).toLocaleDateString(),
      day: getDayName(new Date(Date.now() + 86400000 * 4)),
      tempHigh: 70,
      tempLow: 60,
      condition: 'partly-cloudy',
      precipitation: 20,
      humidity: 60,
      windSpeed: 7,
    },
    {
      date: new Date(Date.now() + 86400000 * 5).toLocaleDateString(),
      day: getDayName(new Date(Date.now() + 86400000 * 5)),
      tempHigh: 72,
      tempLow: 63,
      condition: 'clear',
      precipitation: 0,
      humidity: 55,
      windSpeed: 6,
    },
    {
      date: new Date(Date.now() + 86400000 * 6).toLocaleDateString(),
      day: getDayName(new Date(Date.now() + 86400000 * 6)),
      tempHigh: 74,
      tempLow: 65,
      condition: 'clear',
      precipitation: 0,
      humidity: 50,
      windSpeed: 5,
    },
  ],
  hourly: [
    { time: '12 AM', temperature: 62, condition: 'clear', precipitation: 0 },
    { time: '1 AM', temperature: 61, condition: 'clear', precipitation: 0 },
    { time: '2 AM', temperature: 60, condition: 'clear', precipitation: 0 },
    { time: '3 AM', temperature: 59, condition: 'partly-cloudy', precipitation: 0 },
    { time: '4 AM', temperature: 58, condition: 'partly-cloudy', precipitation: 0 },
    { time: '5 AM', temperature: 58, condition: 'cloudy', precipitation: 10 },
    { time: '6 AM', temperature: 59, condition: 'cloudy', precipitation: 20 },
    { time: '7 AM', temperature: 61, condition: 'cloudy', precipitation: 20 },
    { time: '8 AM', temperature: 63, condition: 'partly-cloudy', precipitation: 10 },
    { time: '9 AM', temperature: 65, condition: 'partly-cloudy', precipitation: 0 },
    { time: '10 AM', temperature: 68, condition: 'partly-cloudy', precipitation: 0 },
    { time: '11 AM', temperature: 70, condition: 'partly-cloudy', precipitation: 0 },
    { time: '12 PM', temperature: 72, condition: 'partly-cloudy', precipitation: 0 },
    { time: '1 PM', temperature: 73, condition: 'partly-cloudy', precipitation: 0 },
    { time: '2 PM', temperature: 74, condition: 'partly-cloudy', precipitation: 0 },
    { time: '3 PM', temperature: 75, condition: 'partly-cloudy', precipitation: 0 },
    { time: '4 PM', temperature: 74, condition: 'partly-cloudy', precipitation: 0 },
    { time: '5 PM', temperature: 73, condition: 'partly-cloudy', precipitation: 0 },
    { time: '6 PM', temperature: 71, condition: 'partly-cloudy', precipitation: 0 },
    { time: '7 PM', temperature: 69, condition: 'clear', precipitation: 0 },
    { time: '8 PM', temperature: 67, condition: 'clear', precipitation: 0 },
    { time: '9 PM', temperature: 66, condition: 'clear', precipitation: 0 },
    { time: '10 PM', temperature: 65, condition: 'clear', precipitation: 0 },
    { time: '11 PM', temperature: 63, condition: 'clear', precipitation: 0 },
  ],
};

// Mock weather data for different locations
const mockLocationData: Record<string, WeatherData> = {
  'san-francisco': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'San Francisco',
      region: 'California',
      country: 'United States',
      latitude: 37.7749,
      longitude: -122.4194,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 15, // Using Celsius as base now
      feelsLike: 14,
      humidity: 75,
      condition: 'fog',
      description: 'Foggy',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: day.tempHigh - 11, // Converting to Celsius
      tempLow: day.tempLow - 11,
      condition: day.day === 'Today' ? 'fog' as WeatherCondition : day.condition,
    })),
  },
  'london': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'London',
      region: 'Greater London',
      country: 'United Kingdom',
      latitude: 51.5074,
      longitude: -0.1278,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 12, // Celsius
      feelsLike: 10,
      humidity: 80,
      condition: 'rain',
      description: 'Light rain',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: day.tempHigh - 15,
      tempLow: day.tempLow - 13,
      condition: (day.day === 'Today' || day.day === 'Tomorrow' ? 'rain' : day.condition) as WeatherCondition,
      precipitation: day.day === 'Today' || day.day === 'Tomorrow' ? 80 : day.precipitation,
    })),
  },
  'tokyo': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Tokyo',
      region: 'Tokyo',
      country: 'Japan',
      latitude: 35.6762,
      longitude: 139.6503,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 78,
      feelsLike: 80,
      humidity: 70,
      condition: 'clear',
      description: 'Sunny',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: day.tempHigh + 6,
      tempLow: day.tempLow + 8,
      condition: day.day === 'Today' ? 'clear' as WeatherCondition : day.condition,
    })),
  },
  'sydney': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Sydney',
      region: 'New South Wales',
      country: 'Australia',
      latitude: -33.8688,
      longitude: 151.2093,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 70,
      feelsLike: 71,
      humidity: 60,
      condition: 'clear',
      description: 'Sunny',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: day.tempHigh + 2,
      tempLow: day.tempLow + 4,
      condition: day.day === 'Today' ? 'clear' as WeatherCondition : day.condition,
    })),
  },
  
  'dubai': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Dubai',
      region: 'Dubai',
      country: 'United Arab Emirates',
      latitude: 25.2048,
      longitude: 55.2708,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 95,
      feelsLike: 98,
      humidity: 45,
      condition: 'clear',
      description: 'Sunny and hot',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: day.tempHigh + 20,
      tempLow: day.tempLow + 15,
      condition: day.day === 'Today' ? 'clear' as WeatherCondition : day.condition,
      precipitation: day.day === 'Today' ? 0 : day.precipitation,
    })),
  },
  
  'cairo': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Cairo',
      region: 'Cairo Governorate',
      country: 'Egypt',
      latitude: 30.0444,
      longitude: 31.2357,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 90,
      feelsLike: 92,
      humidity: 40,
      condition: 'clear',
      description: 'Hot and dry',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: day.tempHigh + 15,
      tempLow: day.tempLow + 12,
      condition: day.day === 'Today' ? 'clear' as WeatherCondition : day.condition,
    })),
  },
  
  'riyadh': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Riyadh',
      region: 'Riyadh Province',
      country: 'Saudi Arabia',
      latitude: 24.7136,
      longitude: 46.6753,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 99,
      feelsLike: 100,
      humidity: 20,
      condition: 'clear',
      description: 'Very hot',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: day.tempHigh + 22,
      tempLow: day.tempLow + 18,
      condition: day.day === 'Today' ? 'clear' as WeatherCondition : day.condition,
      precipitation: 0,
    })),
  },
  
  'doha': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Doha',
      region: 'Doha',
      country: 'Qatar',
      latitude: 25.2854,
      longitude: 51.5310,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 92,
      feelsLike: 94,
      humidity: 55,
      condition: 'clear',
      description: 'Hot and humid',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: day.tempHigh + 18,
      tempLow: day.tempLow + 14,
      condition: day.day === 'Today' ? 'clear' as WeatherCondition : day.condition,
    })),
  },
  
  'paris': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Paris',
      region: 'Île-de-France',
      country: 'France',
      latitude: 48.8566,
      longitude: 2.3522,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 14,
      feelsLike: 13,
      humidity: 70,
      condition: 'partly-cloudy',
      description: 'Partly cloudy',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 16 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 5) - 2),
      tempLow: 10 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      condition: mockWeatherData.daily[0].condition
    })),
  },
  'berlin': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Berlin',
      region: 'Berlin',
      country: 'Germany',
      latitude: 52.5200,
      longitude: 13.4050,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 11,
      feelsLike: 9,
      humidity: 75,
      condition: 'cloudy',
      description: 'Overcast',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 13 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 4) - 2),
      tempLow: 7 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      condition: mockWeatherData.daily[0].condition
    })),
  },
  'moscow': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Moscow',
      region: 'Moscow',
      country: 'Russia',
      latitude: 55.7558,
      longitude: 37.6173,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 5,
      feelsLike: 2,
      humidity: 85,
      condition: 'snow',
      description: 'Light snow',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 7 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 0 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 2),
      condition: ['snow', 'cloudy', 'partly-cloudy'][Math.floor(Math.random() * 3)] as WeatherCondition,
    })),
  },
  'mumbai': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Mumbai',
      region: 'Maharashtra',
      country: 'India',
      latitude: 19.0760,
      longitude: 72.8777,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 32,
      feelsLike: 35,
      humidity: 80,
      condition: 'clear',
      description: 'Hot and humid',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 33 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2)),
      tempLow: 28 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: day.condition as WeatherCondition,
    })),
  },
  'mexico-city': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Mexico City',
      region: 'CDMX',
      country: 'Mexico',
      latitude: 19.4326,
      longitude: -99.1332,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 23,
      feelsLike: 24,
      humidity: 60,
      condition: 'clear',
      description: 'Sunny',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 25 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 18 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: mockWeatherData.daily[0].condition
    })),
  },
  'sao-paulo': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'São Paulo',
      region: 'São Paulo',
      country: 'Brazil',
      latitude: -23.5505,
      longitude: -46.6333,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 27,
      feelsLike: 29,
      humidity: 75,
      condition: 'rain',
      description: 'Tropical rain',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 29 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 22 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: ['rain', 'showers', 'cloudy'][Math.floor(Math.random() * 3)] as WeatherCondition,
    })),
  },
  'marrakech': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'مراكش',  // Marrakech in Arabic
      region: 'Marrakech-Safi',
      country: 'Morocco',
      latitude: 31.6295,
      longitude: -7.9811,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 33,
      feelsLike: 34,
      humidity: 30,
      condition: 'clear',
      description: 'Hot and dry',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 36 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 22 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: 'clear' as WeatherCondition,
    })),
  },
  
  // Let's add more regions in Morocco
  'casablanca': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'الدار البيضاء',  // Casablanca in Arabic
      region: 'Casablanca-Settat',
      country: 'Morocco',
      latitude: 33.5731,
      longitude: -7.5898,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 25,
      feelsLike: 26,
      humidity: 70,
      condition: 'partly-cloudy',
      description: 'Partly cloudy with sea breeze',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 28 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 20 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: 'partly-cloudy' as WeatherCondition,
    })),
  },
  
  'fes': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'فاس',  // Fes in Arabic
      region: 'Fès-Meknès',
      country: 'Morocco',
      latitude: 34.0181,
      longitude: -5.0078,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 29,
      feelsLike: 30,
      humidity: 45,
      condition: 'clear',
      description: 'Sunny and warm',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 32 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 18 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: 'clear' as WeatherCondition,
    })),
  },
  
  'tangier': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'طنجة',  // Tangier in Arabic
      region: 'Tanger-Tétouan-Al Hoceima',
      country: 'Morocco',
      latitude: 35.7595,
      longitude: -5.8340,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 24,
      feelsLike: 25,
      humidity: 75,
      condition: 'cloudy',
      description: 'Cloudy with Mediterranean influence',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 26 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 19 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: 'cloudy' as WeatherCondition,
    })),
  },
  
  'agadir': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'أكادير',  // Agadir in Arabic
      region: 'Souss-Massa',
      country: 'Morocco',
      latitude: 30.4278,
      longitude: -9.5981,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 23,
      feelsLike: 24,
      humidity: 70,
      condition: 'partly-cloudy',
      description: 'Mild coastal weather',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 25 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      tempLow: 17 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: 'partly-cloudy' as WeatherCondition,
    })),
  },
  'beijing': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: '北京', // Beijing in Chinese
      region: 'Beijing',
      country: 'China',
      latitude: 39.9042,
      longitude: 116.4074,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 28,
      feelsLike: 30,
      humidity: 60,
      condition: 'partly-cloudy',
      description: 'Partly cloudy',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 30 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 22 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: mockWeatherData.daily[0].condition
    })),
  },
  'istanbul': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'İstanbul',
      region: 'Istanbul',
      country: 'Turkey',
      latitude: 41.0082,
      longitude: 28.9784,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 21,
      feelsLike: 22,
      humidity: 65,
      condition: 'partly-cloudy',
      description: 'Partly cloudy',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 23 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 16 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: mockWeatherData.daily[0].condition
    })),
  },
  'buenos-aires': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Buenos Aires',
      region: 'Buenos Aires',
      country: 'Argentina',
      latitude: -34.6037,
      longitude: -58.3816,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 15,
      feelsLike: 14,
      humidity: 70,
      condition: 'partly-cloudy',
      description: 'Partly cloudy',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 17 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 10 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: mockWeatherData.daily[0].condition
    })),
  },
  'cape-town': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'Cape Town',
      region: 'Western Cape',
      country: 'South Africa',
      latitude: -33.9249,
      longitude: 18.4241,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 18,
      feelsLike: 17,
      humidity: 75,
      condition: 'partly-cloudy',
      description: 'Partly cloudy',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 20 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 12 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: mockWeatherData.daily[0].condition
    })),
  },
  'bangkok': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'กรุงเทพมหานคร', // Bangkok in Thai
      region: 'Bangkok',
      country: 'Thailand',
      latitude: 13.7563,
      longitude: 100.5018,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 30,
      feelsLike: 32,
      humidity: 70,
      condition: 'partly-cloudy',
      description: 'Partly cloudy',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 32 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 24 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: mockWeatherData.daily[0].condition
    })),
  },
  'jerusalem': {
    ...mockWeatherData,
    location: {
      ...mockWeatherData.location,
      name: 'ירושלים', // Jerusalem in Hebrew
      region: 'Jerusalem District',
      country: 'Israel',
      latitude: 31.7683,
      longitude: 35.2137,
    },
    current: {
      ...mockWeatherData.current,
      temperature: 26,
      feelsLike: 27,
      humidity: 55,
      condition: 'clear',
      description: 'Sunny',
    },
    daily: mockWeatherData.daily.map(day => ({
      ...day,
      tempHigh: 28 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 3) - 1),
      tempLow: 18 + (day.day === 'Today' ? 0 : Math.floor(Math.random() * 2) - 1),
      condition: mockWeatherData.daily[0].condition
    })),
  },
};

// Mock location search results
const mockSearchResults: LocationSearchResult[] = [
  {
    id: 'new-york',
    name: 'New York',
    region: 'New York',
    country: 'United States',
    latitude: 40.7128,
    longitude: -74.0060,
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    region: 'California',
    country: 'United States',
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    id: 'london',
    name: 'London',
    region: 'Greater London',
    country: 'United Kingdom',
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    region: 'Tokyo',
    country: 'Japan',
    latitude: 35.6762,
    longitude: 139.6503,
  },
  {
    id: 'sydney',
    name: 'Sydney',
    region: 'New South Wales',
    country: 'Australia',
    latitude: -33.8688,
    longitude: 151.2093,
  },
